### ISSUE TITLE
Tag the library & bump cocoapods version

### ISSUE THREAD

**Issue by ldiqual** [dbowen/NSAttributedString-DDHTML#13]
Current podspec (https://github.com/CocoaPods/Specs/blob/master/Specs/NSAttributedString-DDHTML/0.0.1/NSAttributedString-DDHTML.podspec.json) is related to commit 03c0ec124e424aeb37fbf05a31048f51c7d65b22, which is 1.5 year old.

Would it be possible to tag the library to `1.0` and publish an official podspec?
Thanks so much for the great work.

**Comment by dbowen** [comment]
I've created the pod spec and tag.  I will push the trunk to cocoa pods shortly.

**Comment by dbowen** [comment]
v1.0 is now available through CocoaPods.

**Comment by ldiqual** [comment]
@dbowen Thanks! Works perfectly.
