### ISSUE TITLE
Error in one of the method. 

### ISSUE THREAD

**Issue by hagile** [dbowen/NSAttributedString-DDHTML#16]
![screen shot 2015-11-18 at 3 50 02 pm](https://cloud.githubusercontent.com/assets/11436406/11238524/532a2806-8e0c-11e5-8e38-ead6caf348fa.png)

`+ (NSAttributedString *)attributedStringFromHTML:(NSString *)htmlString normalFont:(UIFont  *)normalFont boldFont:(UIFont *)boldFont italicFont:(UIFont *)italicFont imageMap:(NSDictionary<NSString *, UIImage *> *)imageMap;`

**Comment by dbowen** [comment]
This occurs because 1.2.0 requires Xcode 7 or greater for Objective-C generics.  Please continue to use v1.1.0 if you need to support older Xcode versions, or simply remove the generics identifier in your local copy.
