### ISSUE TITLE
<a> missing href crash

### ISSUE THREAD

**Issue by pedro380085** [dbowen/NSAttributedString-DDHTML#29]
I know it is a faulty html structure, but shouldn't the parser just ignore it?

Basically when you have something like this `<p><a>Text</a></p>` leads the code into a crash scenario, because:

```
NSString *link = attributeDictionary[@"href"];
[nodeAttributedString addAttribute:NSLinkAttributeName value:link range:NSMakeRange(0, title.length)];
```

*link is never checked if it is valid or not.

**Comment by tywhang** [comment]
My company ran into the same issue and have a PR out for this.
